### ISSUE TITLE
[BUG] Marketplaces doesn't load

### ISSUE THREAD

**Issue by mkarreth** [FlowiseAI/Flowise#1793]
**Describe the bug**
In the latest update on Mac in Safari, when navigating from home to Marketplaces page, the page loads blank.

**To Reproduce**

1. Launch Flowise go to localhost 3000
2. Click on Marketplaces in the side bar
3. See empty page

**Comment by Jaredude** [comment]
Are you able to share an entry in the server error log?

**Comment by Rai-Sahil** [comment]
Hi there, I successfully ran my application on localhost:3000 using both Yarn and Docker Compose. It's working flawlessly in both environments. 
Mac: M2 Pro
Browser: Safari

@mkarreth Could you give a little more description about this? 

<img width="562" alt="Screenshot 2024-02-26 at 2 20 51 AM" src="https://github.com/FlowiseAI/Flowise/assets/78111534/1fa3b77d-333b-4fa9-88a6-47846a3462ef">

<img width="1182" alt="Screenshot 2024-02-26 at 2 20 58 AM" src="https://github.com/FlowiseAI/Flowise/assets/78111534/ced44091-2ad6-4011-b7f2-cb9444fc585a">

**Comment by Renegate** [comment]
@Rai-Sahil Here is what I found. On the clean VM everything works fine, but on my mac after upgrading 1.5.0 -> 1.5.1 marketplaces page fails with following error:
![image](https://github.com/FlowiseAI/Flowise/assets/12396714/b528d3bb-bf06-468b-a33c-93a794e5567a)

And this happens because of this:
![image](https://github.com/FlowiseAI/Flowise/assets/12396714/8bc11b0d-d30e-45a2-bede-a7695a27315b)

Payload should return data object instead there is page

**Comment by Rai-Sahil** [comment]
@Renegate Thanks for Clarification.

I ran v1.5.1 as well. But somehow it still seems fine to me. I ran flowise first by installing the v1.5.1 code and then by installing it globally with npm. 

<img width="518" alt="Screenshot 2024-02-27 at 6 20 13 AM" src="https://github.com/FlowiseAI/Flowise/assets/78111534/1cbf3f9a-618d-4a40-bce1-bfc98f9c7359">


In both the scenarios it seems good tbh. I guess I'm running it wrong. Can I ask you how did you ran it?

**Comment by mkarreth** [comment]
Sorry for delay here. Here the console logs for when Safari doesn't load it. I am on 1.5.1.

Looks like a portion of the react has a height attribute error (rem vs. em).

```
[Error] Error: Invalid value for <svg> attribute height="1.3rem"
	b (main.7ab397e2.js:2:423022)
	Kl (main.7ab397e2.js:2:506793)
	xc (main.7ab397e2.js:2:529205)
	wc (main.7ab397e2.js:2:529086)
	yc (main.7ab397e2.js:2:528953)
	vc (main.7ab397e2.js:2:528816)
	cc (main.7ab397e2.js:2:525932)
	Ho (main.7ab397e2.js:2:466526)
	(anonymous function) (main.7ab397e2.js:2:523529)
[Error] SyntaxError: JSON Parse error: Unexpected identifier "undefined"
parse
(anonymous function) — index.js:119
os — react-dom.production.min.js:244:332
Sc — react-dom.production.min.js:286:114
(anonymous function) — react-dom.production.min.js:282:391
k — scheduler.production.min.js:13:205
T — scheduler.production.min.js:14:128

	(anonymous function) (6708.90a40146.chunk.js:1:2854)
	os (main.7ab397e2.js:2:513386)
	Sc (main.7ab397e2.js:2:533614)
	(anonymous function) (main.7ab397e2.js:2:530204)
	k (main.7ab397e2.js:2:580037)
	T (main.7ab397e2.js:2:580571)
[Error] TypeError: undefined is not a function (near '...F.data.map...')
(anonymous function) — index.js:158
map
k — index.js:152
_i — react-dom.production.min.js:167:139
Ol — react-dom.production.min.js:197:261
wc — react-dom.production.min.js:280:392
yc — react-dom.production.min.js:280:323
vc — react-dom.production.min.js:280:180
ic — react-dom.production.min.js:271:91
ac — react-dom.production.min.js:268:432
k — scheduler.production.min.js:13:205
T — scheduler.production.min.js:14:128

	fl (main.7ab397e2.js:2:491500)
	(anonymous function) (main.7ab397e2.js:2:491726)
	Wa (main.7ab397e2.js:2:473142)
	xs (main.7ab397e2.js:2:521094)
	ws (main.7ab397e2.js:2:520527)
	bs (main.7ab397e2.js:2:520063)
	(anonymous function) (main.7ab397e2.js:2:531900)
	kc (main.7ab397e2.js:2:532413)
	ac (main.7ab397e2.js:2:524873)
	k (main.7ab397e2.js:2:580037)
	T (main.7ab397e2.js:2:580571)
[Error] TypeError: undefined is not a function (near '...F.data.map...')
	(anonymous function) (main.7ab397e2.js:2:532323)
	kc (main.7ab397e2.js:2:532413)
	ac (main.7ab397e2.js:2:524873)
	k (main.7ab397e2.js:2:580037)
	T (main.7ab397e2.js:2:580571)
```

**Comment by Renegate** [comment]
Alright, for me this steps solves the problem: `npm cache clean --force` and  `npm install -g flowise -f`

**Comment by mkarreth** [comment]
Negative, still not loading on my end. I am on 1.6.0 now.

Dug a bit more seems to be similar type errors in the marketplaces index.js. 

<img width="909" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/33272385/0e9024ae-72f3-46ef-a4d3-cd3cd62c4313">

```
index.js:131 SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at index.js:119:43
    
   TypeError: F.data.map is not a function
    at index.js:158:73
    
  ncaught TypeError: F.data.map is not a function
    at index.js:158:73
```

**Comment by EasyAINow** [comment]
I have the same problem, except it does it for both Marketplaces and Variables

**Comment by Rai-Sahil** [comment]
Hmm...

Interestingly, I ran it every way listed and somehow it still works fine for me. Strange.
<img width="566" alt="Screenshot 2024-02-28 at 8 09 12 AM" src="https://github.com/FlowiseAI/Flowise/assets/78111534/9f3950e8-ebd4-4474-9cc1-6dac96ce68f6">

**Comment by HenryHengZJ** [comment]
In the latest release version, this should be fixed by this [PR](https://github.com/FlowiseAI/Flowise/pull/1799)

**Comment by chrismaki** [comment]
@0sbx1 Did you ever get this sorted out? I tried installing Flowise via npm for the first time yesterday and am still seeing this issue, only on the Marketplaces tab. Refreshing repeatedly shows that it does render initially, but then gets wiped. Inspector timeline confirms the same.

**Comment by thomasbraun2014** [comment]
same problem with 
![image](https://github.com/user-attachments/assets/ee0865b7-5c81-4ef7-ab2a-94fad6b1a274)

**Comment by chrismaki** [comment]
I ended up removing the npm version and installing this via Docker and the Marketplace tab loads fine now.

**Comment by hyunmiCho** [comment]
![image](https://github.com/user-attachments/assets/e08e4993-285e-4c18-91be-d3c1e1e830f5)

help me

**Comment by thomasbraun2014** [comment]
i solved my problem with downgrade node.js from v23.00 to  node-v20.18.0-x64

**Comment by MauricioNicolau007** [comment]
Como resolver o meu problema de que o meu flowise depois de criar um projecto não abre o chat de mensagem e o meu martplace no flowise não abre

**Comment by MauricioNicolau007** [comment]
Obrigado , deu certo e agora está funcionando corretamente...

**Comment by MauricioNicolau007** [comment]
Obrigado , deu certo e agora está funcionando corretamente...

**Comment by iAmVSJ0702** [comment]
i know but this problem genuinely occurred to me and by doing that fix it solved so i posted, if you find more effective fix that plz let me know

**Comment by Kalin-Konstantinov** [comment]
I bypass the bug by installing version 20.18.1 on node and then just running flowise and letting it download version 2.2.2.
To use different versions of node, you can use nvm, install whatever versions you want, and then enable the appropriate one with nvm use <version>.
So you can download nvm for windos from here:
https://github.com/coreybutler/nvm-windows/releases 
I`ve used exe file.
after open cmd(type cmd in windows serch)
in cmd write: nvm install 20.18.1
and after: nvm use 20.18.1
to check avaible versions you can type: nvm list
and if you wont to see other commands in nvm just type: nvm

**Comment by joeyk16** [comment]
I had the same issue:

1. `nvm use 20` install Node version manager
2. `npx flowise start` it will ask you to download an old version, say yes.

Bingo! I can now go to /marketplace
