### ISSUE TITLE
[BUG] After upgrade 1.6.6 - PineconeArgumentError: The client configuration had validation errors: argument must NOT have additional properties.

### ISSUE THREAD

**Issue by bendadaniel** [FlowiseAI/Flowise#2316]
Hello,
I have just upgraded to version 1.6.6. 

After upgrade I am getting error:
`PineconeArgumentError: The client configuration had validation errors: argument must NOT have additional properties.`

Workflow worked well before upgrade. I tried remove Pinecode node and configure it again but still same error.

Do you have idea where could be problem?

Thank you Daniel

<img width="401" alt="Screenshot 2024-05-04 at 17 00 10" src="https://github.com/FlowiseAI/Flowise/assets/15817021/0b0efc8b-a5da-41a3-922a-960b4d13dfb4">
<img width="1427" alt="Screenshot 2024-05-04 at 16 59 12" src="https://github.com/FlowiseAI/Flowise/assets/15817021/8524806a-d10b-46ed-8e3a-d9e41323c075">

**Comment by HenryHengZJ** [comment]
I'm not sure will this solve the issue, but if you delete the existing pinecone node, and re-drag it from the menu again, does that works?

**Comment by bendadaniel** [comment]
> I'm not sure will this solve the issue, but if you delete the existing pinecone node, and re-drag it from the menu again, does that works?

No, I have already tried it.

**Comment by bendadaniel** [comment]
I have just tried for test create brand new workflow with same nodes and configuration, but it still doenst work.

**Comment by alekzan** [comment]
Same Issue here

**Comment by HenryHengZJ** [comment]
How are you running Flowise? Wanted to see if I can replicate it

**Comment by bendadaniel** [comment]
I am running it on render.com, rly basic setup, nothing special (https://docs.flowiseai.com/configuration/deployment/render).

**Comment by HenryHengZJ** [comment]
@bendadaniel try redeploying, it should now works with the [PR](https://github.com/FlowiseAI/Flowise/pull/2322) merged

**Comment by bendadaniel** [comment]
Fixed, thank you.

**Comment by mdmanalytics** [comment]
Still getting this issue on 5/8/24. Running local instance of Flowise.
