### ISSUE TITLE
[BUG] Collect Lead Not Working For More Than One User

### ISSUE THREAD

**Issue by AsharibAli** [FlowiseAI/Flowise#2321]
I was trying out the new "Collect Lead" feature implemented by @0xi4o and encountered the following issue:

The lead form only works once, meaning that after someone fills out the lead form, it does not reappear for anyone else. I tested this using the built-in chat and the embed option, both in production and development environments. However, the form fails to show after being filled out a single time. 

@0xi4o , could you please investigate this issue? If I am making a mistake, kindly inform me. 

Thank you.

**Comment by HenryHengZJ** [comment]
once the lead is filled out, it will saved into local storage so it prevents the same user to see the lead form everytime. Now, if you try opening up in an microsoft edge, or igconito chrome, you should see the form

**Comment by AsharibAli** [comment]
Thank you @HenryHengZJ. I understand but there is an issue with the submit button of the Form Lead via the embed option. It seems that the button is not working at all and is calling an endpoint on localhost which does not exist. The form only seems to be working on the production flowise dashboard and not via the API/Embed option. When we click on the submit button with the blue arrow, it calls the endpoint which is causing the issue.

`POST http://localhost:3000/api/v1/leads/ net::ERR_FAILED`

**Comment by HenryHengZJ** [comment]
@AsharibAli this should be resolved can you try again?

**Comment by titogarrido** [comment]
I am using the latest version of the https://github.com/FlowiseAI/FlowiseChatEmbed and it is still calling localhost:3000

**Comment by AsharibAli** [comment]
> @AsharibAli this should be resolved can you try again?

The bug is not resolved, it's still calling the same API endpoint(POST Request), which doesn't exist. 

Dear @0xi4o could you please look at it, just because you implemented this feature, you know it very well than us.

**Comment by titogarrido** [comment]
Somehow the `apiHost` variable is not being used for the "lead" call.

**Comment by 0xi4o** [comment]
@titogarrido Yep you're right. `apiHost` from configuration was not being used.

cc: @AsharibAli

I've opened a PR with the fix: https://github.com/FlowiseAI/FlowiseChatEmbed/pull/152

**Comment by AsharibAli** [comment]
Amazing 🔥
