### ISSUE TITLE
[BUG] Multi-Agent Flow Stops Abruptly

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#2580]
**Describe the bug**
Agent flow stops abruptly when conveying message to Worker

**To Reproduce**

1. Connect a Chat Model to Supervisor Agent
2. Connect a Supervisor Agent to Worker
3. Submit a chat query
4. See error (Message Stopped)

**Expected behavior**
Supervisor should convey user message to worker

**Screenshots**
<img width="1440" alt="AgentFlow-Error" src="https://github.com/FlowiseAI/Flowise/assets/129256153/fa0c3145-8fec-4ae4-84c0-9e65b867c340">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Render Cloud Service (Instance Type: Standard)
-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [latest]
-   OS: [macOS M1]
-   Browser [chrome]

**Additional context**

**Comment by WizKid1968** [comment]
> More users are reporting the same here #2557
> 
> Edit: here is the fix [#2557 (comment)](https://github.com/FlowiseAI/Flowise/issues/2557#issuecomment-2148208490)

Thanks!

**Comment by HenryHengZJ** [comment]
Should be fixed in latest version, are you sure you are on latest 1.8.1 ?

**Comment by HenryHengZJ** [comment]
Closing now and move to #2557

**Comment by execo-h** [comment]
Hi, am on 1.8.2 and still seeing the "Message Stopped" error
