### ISSUE TITLE
[BUG] Multiple agents on the same flow, unable to assign different custom tools

### ISSUE THREAD

**Issue by loziobiz** [FlowiseAI/Flowise#4566]
**Describe the bug**
When more than one agent are used on the same agentflow, setting a custom tool in one agent causes other agents to use the same tool.

**To Reproduce**

1. Create a new agentflow
2. Add two agent nodes
3. Open the first agent settings and assign a custom tool to it
4. Open the second agent and assign a different custom tool
5. Re-open the first agent. Custom tool assigned is now the same as the second agent

**Expected behavior**
Each agent should be capable to have  independent custom tools

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation: `npx flowise start`
-   Flowise Version: flowiseai/flowise:3.0.1
-   OS: macOS
-   Browser: chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
fixed: https://github.com/FlowiseAI/Flowise/pull/4548

will be pushed to 3.0.2 soon

**Comment by JokaHD** [comment]
Hello,
I tested this again on tag `flowise@3.0.2` and I'm still encountering the same issue.
When using the Custom MCP Tool, the problem now occurs intermittently rather than 100% of the time.
However, when using the OpenAPI Toolkit, the issue can be consistently reproduced — the YAML file gets overwritten by the most recently uploaded one every time.

@loziobiz  Just checking — has this issue been resolved on your side?

#### Setup
Installation: `pnpm build && pnpm dev`
Flowise Version: tag `flowise@3.0.2`
OS: macOS
Browser: chrome
